### ISSUE TITLE
Error using show option in rootangle_tree(tree, '-s')

### ISSUE THREAD

**Issue by natsrm** [cuntzlab/treestoolbox#4]
Hi! I was looking at the paper "Dissecting Sholl Analysis into its functional components" and wanted to use the rootangle_tree function with the show option, but I get the following error message:

`rootangle_tree(sample_tree, '-s')`

**`Error using trapz (line 58)`**
**`LENGTH(X) must equal the length of Y in dim 2.`**

**`Error in rootangle_tree (line 80)`**
**`   plot(mAngV,pdf/trapz(AngV,pdf),'black')`**

I went to look into the code for root angle and it seems the variable AngV is a 1x25 double, while mAngV and pdf are both 1x24 doubles, which is what causes this error. Could this be a code error or maybe is it due to the matlab version I'm using? (R2016b)

To try to "go around" the generated error, I did the plot by using:

`plot(mAngV, pdf/trapz(AngV(1:24), pdf), 'black')`

which does generate a plot, but I am not sure if it is correct, since it does not start in x=0 like the plots in Figure 3C from the paper.

![image](https://user-images.githubusercontent.com/43876521/61641915-e4ca1980-ac97-11e9-8e02-ccc66c36ff0a.png)

The plot is also exactly the same if instead of using AngV(1:24), I use AngV(2:25).

![image](https://user-images.githubusercontent.com/43876521/61641966-ff03f780-ac97-11e9-917e-c3265eef3f59.png)

 I would very much appreciate your input about the plot, if I can do it like this or if it needs to be another way! :)

**Comment by hermanncuntz** [comment]
The problem seems to come from the changing use of 'hist', 'histc', and 'histcounts' between different versions of Matlab. The more recent version of 'histcounts' takes the edges of the bins as an argument and so the output is smaller than the input by one. The 'trapz' part of the plot line normalises the pdf and so taking either of your solutions is correct. The most consistent approach would be to write 'trapz(mAngV,pdf)' instead of 'trapz(AngV,pdf)'. We will update the '-s' functionality soon to correct this.

**Comment by natsrm** [comment]
@hermanncuntz thank you so much for your clarification!
